// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AboutOps struct {
	CreateEducation          *Education         `json:"create_education"`
	CreateWorkingExperience  *WorkingExperience `json:"create_working_experience"`
	CreateBuiltProjects      *BuiltProject      `json:"create_built_projects"`
	UpdateEducation          *Education         `json:"update_education"`
	UpdateWorkingExperience  *WorkingExperience `json:"update_working_experience"`
	UpdateBuiltProjects      *BuiltProject      `json:"update_built_projects"`
	DeleteEducation          int                `json:"delete_education"`
	DeleteWorkingExprerience int                `json:"delete_working_exprerience"`
	DeleteBuiltProjects      int                `json:"delete_built_projects"`
	CreateEducationCategory  *EducationCategory `json:"create_education_category"`
	UpdateEducationCategory  *EducationCategory `json:"update_education_category"`
	DeleteEducationCategory  int                `json:"delete_education_category"`
}

type AboutQuery struct {
	Education                []*EducationCategory `json:"education"`
	WorkingExperience        []*WorkingExperience `json:"working_experience"`
	BuiltProjects            []*BuiltProject      `json:"built_projects"`
	EducationWithoutCategory []*Education         `json:"education_without_category"`
}

type Audio struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Author string `json:"author"`
	Src    string `json:"src"`
	Cover  string `json:"cover"`
	OnDuty int    `json:"on_duty"`
	Sizes  *File  `json:"sizes"`
}

type AudioOps struct {
	Create *Audio `json:"create"`
	Update *Audio `json:"update"`
	Delete int    `json:"delete"`
}

type BuiltProject struct {
	ID             int    `json:"id"`
	Thumbnail      string `json:"thumbnail"`
	Name           string `json:"name"`
	Overview       string `json:"overview"`
	GithubLink     string `json:"github_link"`
	DeploymentLink string `json:"deployment_link"`
	OnDuty         int    `json:"on_duty"`
}

type ContactOps struct {
	Mail                  string           `json:"mail"`
	UpdateSocialMediaInfo *SocialMediaInfo `json:"update_social_media_info"`
}

type ContactQuery struct {
	SocialMediaInfo *SocialMediaInfo `json:"social_media_info"`
	Messages        []*Mail          `json:"messages"`
}

type EditSocialMediInfo struct {
	ID        int    `json:"id"`
	Phone     string `json:"phone"`
	Mail      string `json:"mail"`
	Location  string `json:"location"`
	Instagram string `json:"instagram"`
	Whatsapp  string `json:"whatsapp"`
}

type EditedAudio struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Author string `json:"author"`
	Src    string `json:"src"`
	Cover  string `json:"cover"`
	OnDuty int    `json:"on_duty"`
}

type EditedBuiltProject struct {
	ID             int    `json:"id"`
	Thumbnail      string `json:"thumbnail"`
	Name           string `json:"name"`
	Overview       string `json:"overview"`
	GithubLink     string `json:"github_link"`
	DeploymentLink string `json:"deployment_link"`
	OnDuty         int    `json:"on_duty"`
}

type EditedEducation struct {
	ID                  int    `json:"id"`
	Name                string `json:"name"`
	Link                string `json:"link"`
	Logo                string `json:"logo"`
	Image               string `json:"image"`
	StartYear           string `json:"start_year"`
	EndYear             string `json:"end_year"`
	Address             string `json:"address"`
	EducationCategoryID int    `json:"education_category_id"`
	OnDuty              int    `json:"on_duty"`
}

type EditedEducationCategory struct {
	ID     int    `json:"id"`
	Logo   string `json:"logo"`
	Title  string `json:"title"`
	OnDuty int    `json:"on_duty"`
}

type EditedHome struct {
	ID          int    `json:"id"`
	Logo        string `json:"logo"`
	Profession  string `json:"profession"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type EditedImagesCategory struct {
	ID       int    `json:"id"`
	Category string `json:"category"`
	OnDuty   int    `json:"on_duty"`
}

type EditedPhoto struct {
	ID               int    `json:"id"`
	Src              string `json:"src"`
	Width            int    `json:"width"`
	Height           int    `json:"height"`
	ImagesCategoryID int    `json:"images_category_id"`
	OnDuty           int    `json:"on_duty"`
}

type EditedProgrammingLanguage struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Value  int    `json:"value"`
	Color  string `json:"color"`
	Total  int    `json:"total"`
	OnDuty int    `json:"on_duty"`
}

type EditedSkill struct {
	ID     int     `json:"id"`
	Logo   string  `json:"logo"`
	Name   string  `json:"name"`
	State  float64 `json:"state"`
	OnDuty int     `json:"on_duty"`
}

type EditedTopImage struct {
	ID      int    `json:"id"`
	Src     string `json:"src"`
	Caption string `json:"caption"`
	OnDuty  int    `json:"on_duty"`
}

type EditedVideo struct {
	ID     int    `json:"id"`
	Src    string `json:"src"`
	OnDuty int    `json:"on_duty"`
}

type EditedWorkingExperience struct {
	ID          int    `json:"id"`
	CompanyLogo string `json:"company_logo"`
	CompanyName string `json:"company_name"`
	Address     string `json:"address"`
	StartDate   string `json:"start_date"`
	Image       string `json:"image"`
	EndDate     string `json:"end_date"`
	Position    string `json:"position"`
	Overview    string `json:"overview"`
	Description string `json:"description"`
	OnDuty      int    `json:"on_duty"`
}

type Education struct {
	ID                  int                `json:"id"`
	Name                string             `json:"name"`
	Link                string             `json:"link"`
	Logo                string             `json:"logo"`
	Image               string             `json:"image"`
	StartYear           string             `json:"start_year"`
	EndYear             string             `json:"end_year"`
	Address             string             `json:"address"`
	EducationCategoryID int                `json:"education_category_id"`
	OnDuty              int                `json:"on_duty"`
	Category            *EducationCategory `json:"category"`
}

type EducationCategory struct {
	ID     int          `json:"id"`
	Logo   string       `json:"logo"`
	Title  string       `json:"title"`
	OnDuty int          `json:"on_duty"`
	Nodes  []*Education `json:"nodes"`
}

type File struct {
	Small      string `json:"small"`
	Medium     string `json:"medium"`
	Large      string `json:"large"`
	ExtraLarge string `json:"extra_large"`
}

type GalleryOps struct {
	CreateTopImage      *TopImage       `json:"create_top_image"`
	CreateImageCategory *ImagesCategory `json:"create_image_category"`
	CreateImage         *Photo          `json:"create_image"`
	UpdateTopImage      *TopImage       `json:"update_top_image"`
	UpdateImageCategory *ImagesCategory `json:"update_image_category"`
	UpdateImage         *Photo          `json:"update_image"`
	DeleteTopImage      int             `json:"delete_top_image"`
	DeleteImage         int             `json:"delete_image"`
	DeleteImageCategory int             `json:"delete_image_category"`
	Video               *VideoOps       `json:"video"`
	Audio               *AudioOps       `json:"audio"`
}

type GalleryQuery struct {
	CarouselPhotos        []*TopImage       `json:"carousel_photos"`
	TabsPhotos            []*ImagesCategory `json:"tabs_photos"`
	Videos                []*Video          `json:"videos"`
	Audios                []*Audio          `json:"audios"`
	PhotosWithoutCategory []*Photo          `json:"photos_without_category"`
}

type Home struct {
	ID          int    `json:"id"`
	Logo        string `json:"logo"`
	Profession  string `json:"profession"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type HomeOps struct {
	Update *Home `json:"update"`
}

type HomeQuery struct {
	GetInfo *Home `json:"get_info"`
}

type ImagesCategory struct {
	ID       int      `json:"id"`
	Category string   `json:"category"`
	OnDuty   int      `json:"on_duty"`
	Photos   []*Photo `json:"photos"`
}

type Mail struct {
	ID           int         `json:"id"`
	Message      string      `json:"message"`
	SubscriberID int         `json:"subscriber_id"`
	Subscriber   *Subscriber `json:"subscriber"`
}

type MailInput struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	Message     string `json:"message"`
	PhoneNumber string `json:"phone_number"`
}

type NewAudio struct {
	Title  string `json:"title"`
	Author string `json:"author"`
	Src    string `json:"src"`
	Cover  string `json:"cover"`
}

type NewBuiltProject struct {
	Thumbnail      string `json:"thumbnail"`
	Name           string `json:"name"`
	Overview       string `json:"overview"`
	GithubLink     string `json:"github_link"`
	DeploymentLink string `json:"deployment_link"`
	OnDuty         int    `json:"on_duty"`
}

type NewEducation struct {
	Name                string `json:"name"`
	Link                string `json:"link"`
	Logo                string `json:"logo"`
	Image               string `json:"image"`
	StartYear           string `json:"start_year"`
	EndYear             string `json:"end_year"`
	Address             string `json:"address"`
	EducationCategoryID int    `json:"education_category_id"`
	OnDuty              int    `json:"on_duty"`
}

type NewEducationCategory struct {
	Logo  string `json:"logo"`
	Title string `json:"title"`
}

type NewImagesCategory struct {
	Category string `json:"category"`
}

type NewPhoto struct {
	Src              string `json:"src"`
	Width            int    `json:"width"`
	Height           int    `json:"height"`
	ImagesCategoryID int    `json:"images_category_id"`
}

type NewProgrammingLanguage struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
	Color string `json:"color"`
	Total int    `json:"total"`
}

type NewSkill struct {
	Logo  string  `json:"logo"`
	Name  string  `json:"name"`
	State float64 `json:"state"`
}

type NewTopImage struct {
	Src     string `json:"src"`
	Caption string `json:"caption"`
}

type NewVideo struct {
	Src string `json:"src"`
}

type NewWorkingExperience struct {
	CompanyLogo string `json:"company_logo"`
	CompanyName string `json:"company_name"`
	Address     string `json:"address"`
	StartDate   string `json:"start_date"`
	Image       string `json:"image"`
	EndDate     string `json:"end_date"`
	Position    string `json:"position"`
	Overview    string `json:"overview"`
	Description string `json:"description"`
	OnDuty      int    `json:"on_duty"`
}

type Owner struct {
	Username    string `json:"username"`
	AccessToken string `json:"access_token"`
}

type OwnerCredential struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Photo struct {
	ID               int             `json:"id"`
	Src              string          `json:"src"`
	Width            int             `json:"width"`
	Height           int             `json:"height"`
	ImagesCategoryID int             `json:"images_category_id"`
	OnDuty           int             `json:"on_duty"`
	Category         *ImagesCategory `json:"category"`
	Sizes            *File           `json:"sizes"`
}

type ProfileOps struct {
	ProgrammingLanguage *ProgrammingLanguageOps `json:"programming_language"`
	Skill               *SkillOps               `json:"skill"`
}

type ProfileQuery struct {
	ProgrammingLanguages []*ProgrammingLanguage `json:"programming_languages"`
	Skills               []*Skill               `json:"skills"`
}

type ProgrammingLanguage struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Value  int    `json:"value"`
	Color  string `json:"color"`
	Total  int    `json:"total"`
	OnDuty int    `json:"on_duty"`
}

type ProgrammingLanguageOps struct {
	Create *ProgrammingLanguage `json:"create"`
	Update *ProgrammingLanguage `json:"update"`
	Delete int                  `json:"delete"`
}

type Skill struct {
	ID     int     `json:"id"`
	Logo   string  `json:"logo"`
	Name   string  `json:"name"`
	State  float64 `json:"state"`
	OnDuty int     `json:"on_duty"`
}

type SkillOps struct {
	Create *Skill `json:"create"`
	Update *Skill `json:"update"`
	Delete int    `json:"delete"`
}

type SocialMediaInfo struct {
	ID        int    `json:"id"`
	Phone     string `json:"phone"`
	Mail      string `json:"mail"`
	Location  string `json:"location"`
	Instagram string `json:"instagram"`
	Whatsapp  string `json:"whatsapp"`
}

type Subscriber struct {
	ID          int    `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

type TopImage struct {
	ID      int    `json:"id"`
	Src     string `json:"src"`
	Caption string `json:"caption"`
	OnDuty  int    `json:"on_duty"`
	Sizes   *File  `json:"sizes"`
}

type Video struct {
	ID     int    `json:"id"`
	Src    string `json:"src"`
	OnDuty int    `json:"on_duty"`
}

type VideoOps struct {
	Create *Video `json:"create"`
	Update *Video `json:"update"`
	Delete int    `json:"delete"`
}

type WorkingExperience struct {
	ID          int    `json:"id"`
	CompanyLogo string `json:"company_logo"`
	CompanyName string `json:"company_name"`
	Address     string `json:"address"`
	StartDate   string `json:"start_date"`
	Image       string `json:"image"`
	EndDate     string `json:"end_date"`
	Position    string `json:"position"`
	Overview    string `json:"overview"`
	Description string `json:"description"`
	OnDuty      int    `json:"on_duty"`
}
