name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Code"
      uses: "actions/checkout@v2"
        
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    
    - name: Build the Docker image
      env:
        DOCKER_IMAGE_NAME: "louisaldorio/backend-portfolio"
      run: docker build . --file Dockerfile --tag "$DOCKER_IMAGE_NAME":latest
      
    - name: Docker Push
      env:
        DOCKER_IMAGE_NAME: "louisaldorio/backend-portfolio:latest"
      run: docker push  "$DOCKER_IMAGE_NAME"
    
    - name: Update VM Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: ~/test/restart-compose.sh